"""
Quantum Physics Trading Theory Engine

Core Logic:
- If Open Price < Previous Open → Sweep PDL (Down)
- If Open Price > Previous Open → Sweep PDH (Up)

After mission complete (PDL/PDH swept), price follows structure & trend.

Entry Rules:
- UP bias → Entry at Pivot (PP) and S1 (buy zone)
- DOWN bias → Entry at Pivot (PP) and R1 (sell zone)

Validation:
- If DOWN and Open is below Pivot → Entry at Pivot is INVALID (already below)
- If UP and Open is above Pivot → Entry at Pivot is INVALID (already above)
"""

from pivot_calculator import calculate_pivot_points, get_pivot_zone


class QuantumSignal:
    """Represents a trading signal generated by the Quantum Engine."""
    
    def __init__(self, symbol: str, bias: str, entry_levels: list, 
                 invalidation: str, target: str, notes: str):
        self.symbol = symbol
        self.bias = bias  # "UP" or "DOWN"
        self.entry_levels = entry_levels  # list of (level_name, price)
        self.invalidation = invalidation
        self.target = target
        self.notes = notes


class QuantumEngine:
    """
    Quantum Physics Trading Theory Implementation.
    Analyzes market structure based on Open Price comparison and Pivot Points.
    """
    
    def analyze(self, symbol: str, current_open: float, previous_open: float,
                prev_high: float, prev_low: float, prev_close: float,
                prev_day_high: float, prev_day_low: float) -> QuantumSignal:
        """
        Full analysis combining Quantum Theory with Pivot Point entries.
        
        Args:
            symbol: Trading pair (e.g., 'EURUSD', 'BTCUSDT')
            current_open: Today's open price
            previous_open: Yesterday's open price
            prev_high: Previous day high (for pivot calc)
            prev_low: Previous day low (for pivot calc)
            prev_close: Previous day close (for pivot calc)
            prev_day_high: Previous Day High (PDH) - liquidity target
            prev_day_low: Previous Day Low (PDL) - liquidity target
            
        Returns:
            QuantumSignal object with complete analysis
        """
        # Step 1: Determine bias from Quantum Theory
        bias = self._determine_bias(current_open, previous_open)
        
        # Step 2: Calculate Pivot Points
        pivots = calculate_pivot_points(prev_high, prev_low, prev_close)
        
        # Step 3: Determine entry levels with validation
        entry_levels, notes = self._calculate_entries(
            bias, current_open, pivots, prev_day_high, prev_day_low
        )
        
        # Step 4: Determine invalidation and target
        invalidation = self._get_invalidation(bias, pivots, prev_day_high, prev_day_low)
        target = self._get_target(bias, prev_day_high, prev_day_low, pivots)
        
        return QuantumSignal(
            symbol=symbol,
            bias=bias,
            entry_levels=entry_levels,
            invalidation=invalidation,
            target=target,
            notes=notes
        )
    
    def _determine_bias(self, current_open: float, previous_open: float) -> str:
        """
        Quantum Physics Theory:
        - Open < Previous Open → DOWN (Sweep PDL)
        - Open > Previous Open → UP (Sweep PDH)
        """
        if current_open < previous_open:
            return "DOWN"
        elif current_open > previous_open:
            return "UP"
        else:
            return "NEUTRAL"
    
    def _calculate_entries(self, bias: str, current_open: float, 
                           pivots: dict, pdh: float, pdl: float) -> tuple:
        """
        Calculate entry levels based on bias and validate against pivot position.
        
        UP bias → Entry at PP and S1 (buying dips)
        DOWN bias → Entry at PP and R1 (selling rallies)
        
        Validation:
        - DOWN + Open below PP → PP entry INVALID
        - UP + Open above PP → PP entry INVALID
        """
        entry_levels = []
        notes_parts = []
        
        if bias == "UP":
            # UP: Looking to buy at Pivot and S1
            # Validate: If Open is already above Pivot, PP entry is invalid
            if current_open > pivots["PP"]:
                notes_parts.append("⚠️ Open > Pivot → PP entry INVALID (sudah di atas)")
                # Only S1 entry valid
                entry_levels.append(("S1 (Buy Zone)", pivots["S1"]))
                notes_parts.append("✅ S1 masih valid sebagai buy zone")
            else:
                # Both entries valid
                entry_levels.append(("Pivot (Buy Zone)", pivots["PP"]))
                entry_levels.append(("S1 (Buy Zone)", pivots["S1"]))
                notes_parts.append("✅ PP dan S1 valid sebagai buy zone")
            
            notes_parts.append(f"🎯 Mission: Sweep PDH ({pdh})")
            notes_parts.append("📝 Setelah sweep PDH, harga ikut struktur & trend")
            
        elif bias == "DOWN":
            # DOWN: Looking to sell at Pivot and R1
            # Validate: If Open is already below Pivot, PP entry is invalid
            if current_open < pivots["PP"]:
                notes_parts.append("⚠️ Open < Pivot → PP entry INVALID (sudah di bawah)")
                # Only R1 entry valid
                entry_levels.append(("R1 (Sell Zone)", pivots["R1"]))
                notes_parts.append("✅ R1 masih valid sebagai sell zone")
            else:
                # Both entries valid
                entry_levels.append(("Pivot (Sell Zone)", pivots["PP"]))
                entry_levels.append(("R1 (Sell Zone)", pivots["R1"]))
                notes_parts.append("✅ PP dan R1 valid sebagai sell zone")
            
            notes_parts.append(f"🎯 Mission: Sweep PDL ({pdl})")
            notes_parts.append("📝 Setelah sweep PDL, harga ikut struktur & trend")
            
        else:  # NEUTRAL
            notes_parts.append("⚖️ Open = Previous Open → NEUTRAL, tidak ada bias")
            notes_parts.append("⏳ Tunggu konfirmasi arah selanjutnya")
        
        return entry_levels, "\n".join(notes_parts)
    
    def _get_invalidation(self, bias: str, pivots: dict, pdh: float, pdl: float) -> str:
        """Determine invalidation level."""
        if bias == "UP":
            return f"Below S2 ({pivots['S2']})"
        elif bias == "DOWN":
            return f"Above R2 ({pivots['R2']})"
        else:
            return "N/A (Neutral bias)"
    
    def _get_target(self, bias: str, pdh: float, pdl: float, pivots: dict) -> str:
        """Determine target based on bias."""
        if bias == "UP":
            return f"PDH: {pdh} → kemudian R1: {pivots['R1']}"
        elif bias == "DOWN":
            return f"PDL: {pdl} → kemudian S1: {pivots['S1']}"
        else:
            return "N/A"
    
    def format_signal(self, signal: QuantumSignal, pivots: dict) -> str:
        """Format the signal into a Telegram-ready message."""
        
        # Emoji based on bias
        if signal.bias == "UP":
            bias_emoji = "🟢🔼"
            direction = "BULLISH BIAS"
        elif signal.bias == "DOWN":
            bias_emoji = "🔴🔽"
            direction = "BEARISH BIAS"
        else:
            bias_emoji = "⚖️"
            direction = "NEUTRAL"
        
        lines = [
            f"{bias_emoji} *QUANTUM SIGNAL — {signal.symbol}*",
            f"━━━━━━━━━━━━━━━━━━━━━━━━━",
            f"",
            f"📐 *Bias:* `{direction}`",
            f"",
            f"🎯 *Entry Levels:*",
        ]
        
        if signal.entry_levels:
            for name, price in signal.entry_levels:
                lines.append(f"  → {name}: `{price}`")
        else:
            lines.append("  → Tidak ada entry valid saat ini")
        
        lines.extend([
            f"",
            f"🛡️ *Invalidation:* `{signal.invalidation}`",
            f"🏁 *Target:* `{signal.target}`",
            f"",
            f"━━━━━━━━━━━━━━━━━━━━━━━━━",
            f"📊 *Pivot Levels:*",
            f"  R3: `{pivots['R3']}`",
            f"  R2: `{pivots['R2']}`",
            f"  R1: `{pivots['R1']}`",
            f"  PP: `{pivots['PP']}`",
            f"  S1: `{pivots['S1']}`",
            f"  S2: `{pivots['S2']}`",
            f"  S3: `{pivots['S3']}`",
            f"",
            f"━━━━━━━━━━━━━━━━━━━━━━━━━",
            f"📝 *Notes:*",
            f"{signal.notes}",
            f"",
            f"⚠️ _Disclaimer: Bukan financial advice. DYOR!_",
        ])
        
        return "\n".join(lines)
