"""
Quantum Physics Trading Theory Engine + Smart Money Concepts

Core Logic:
- If Open Price < Previous Open → Sweep PDL (Down)
- If Open Price > Previous Open → Sweep PDH (Up)

After mission complete (PDL/PDH swept), price follows structure & trend.

Entry Rules:
- UP bias → Entry at Pivot (PP) and S1 (buy zone)
- DOWN bias → Entry at Pivot (PP) and R1 (sell zone)

Validation:
- If DOWN and Open is below Pivot → Entry at Pivot is INVALID (already below)
- If UP and Open is above Pivot → Entry at Pivot is INVALID (already above)

SMC Confluence (NEW):
- Signals are scored 0-100 based on SMC alignment
- Score >= 50: Valid signal (trade)
- Score < 50: Weak signal (skip or reduce size)
"""

from pivot_calculator import calculate_pivot_points, get_pivot_zone
from smc_engine import SMCEngine, SMCAnalysis


class QuantumSignal:
    """Represents a trading signal generated by the Quantum Engine."""

    def __init__(self, symbol: str, bias: str, entry_levels: list,
                 invalidation: str, target: str, notes: str,
                 smc_analysis: SMCAnalysis = None, smc_filtered: bool = False):
        self.symbol = symbol
        self.bias = bias  # "UP" or "DOWN"
        self.entry_levels = entry_levels  # list of (level_name, price)
        self.invalidation = invalidation
        self.target = target
        self.notes = notes
        self.smc_analysis = smc_analysis  # SMC confluence data
        self.smc_filtered = smc_filtered  # True if signal was filtered by SMC


class QuantumEngine:
    """
    Quantum Physics Trading Theory + Smart Money Concepts.
    Analyzes market structure based on Open Price comparison, Pivot Points,
    and institutional order flow patterns (SMC).
    """

    def __init__(self):
        self.smc = SMCEngine()

    def analyze(self, symbol: str, current_open: float, previous_open: float,
                prev_high: float, prev_low: float, prev_close: float,
                prev_day_high: float, prev_day_low: float,
                candles: list = None) -> QuantumSignal:
        """
        Full analysis combining Quantum Theory + Pivot Points + SMC.

        Args:
            symbol: Trading pair (e.g., 'EURUSD', 'BTCUSDT')
            current_open: Today's open price
            previous_open: Yesterday's open price
            prev_high: Previous day high (for pivot calc)
            prev_low: Previous day low (for pivot calc)
            prev_close: Previous day close (for pivot calc)
            prev_day_high: Previous Day High (PDH) - liquidity target
            prev_day_low: Previous Day Low (PDL) - liquidity target
            candles: (Optional) List of recent daily candles for SMC analysis
                     Each: {open, high, low, close}. If None, SMC is skipped.

        Returns:
            QuantumSignal object with complete analysis + SMC confluence
        """
        # Step 1: Determine bias from Quantum Theory
        bias = self._determine_bias(current_open, previous_open)

        # Step 2: Calculate Pivot Points
        pivots = calculate_pivot_points(prev_high, prev_low, prev_close)

        # Step 3: Determine entry levels with validation
        entry_levels, notes = self._calculate_entries(
            bias, current_open, pivots, prev_day_high, prev_day_low
        )

        # Step 4: Determine invalidation and target
        invalidation = self._get_invalidation(bias, pivots, prev_day_high, prev_day_low)
        target = self._get_target(bias, prev_day_high, prev_day_low, pivots)

        # Step 5: SMC Analysis (if candles provided)
        smc_analysis = None
        smc_filtered = False

        if candles and len(candles) >= 5:
            smc_analysis = self.smc.analyze(
                candles=candles,
                current_price=current_open,
                bias=bias
            )

            # Add SMC info to notes
            if smc_analysis.confluence_score >= 70:
                notes += f"\n\n🔥 *SMC Confluence: {smc_analysis.confluence_score}/100 — HIGH*"
                notes += "\n💪 Strong institutional confirmation!"
            elif smc_analysis.confluence_score >= 50:
                notes += f"\n\n⚡ *SMC Confluence: {smc_analysis.confluence_score}/100 — MEDIUM*"
                notes += "\n👍 Moderate institutional confirmation"
            elif smc_analysis.confluence_score >= 30:
                notes += f"\n\n⚠️ *SMC Confluence: {smc_analysis.confluence_score}/100 — LOW*"
                notes += "\n⚠️ Weak setup — kurangi size atau skip"
                smc_filtered = True
            else:
                notes += f"\n\n❌ *SMC Confluence: {smc_analysis.confluence_score}/100 — NO TRADE*"
                notes += "\n🚫 Tidak ada konfirmasi institutional — SKIP!"
                smc_filtered = True

        return QuantumSignal(
            symbol=symbol,
            bias=bias,
            entry_levels=entry_levels,
            invalidation=invalidation,
            target=target,
            notes=notes,
            smc_analysis=smc_analysis,
            smc_filtered=smc_filtered
        )

    def _determine_bias(self, current_open: float, previous_open: float) -> str:
        """
        Quantum Physics Theory:
        - Open < Previous Open → DOWN (Sweep PDL)
        - Open > Previous Open → UP (Sweep PDH)
        """
        if current_open < previous_open:
            return "DOWN"
        elif current_open > previous_open:
            return "UP"
        else:
            return "NEUTRAL"

    def _calculate_entries(self, bias: str, current_open: float,
                           pivots: dict, pdh: float, pdl: float) -> tuple:
        """
        Calculate entry levels based on bias and validate against pivot position.
        """
        entry_levels = []
        notes_parts = []

        if bias == "UP":
            if current_open > pivots["PP"]:
                notes_parts.append("⚠️ Open > Pivot → PP entry INVALID (sudah di atas)")
                entry_levels.append(("S1 (Buy Zone)", pivots["S1"]))
                notes_parts.append("✅ S1 masih valid sebagai buy zone")
            else:
                entry_levels.append(("Pivot (Buy Zone)", pivots["PP"]))
                entry_levels.append(("S1 (Buy Zone)", pivots["S1"]))
                notes_parts.append("✅ PP dan S1 valid sebagai buy zone")

            notes_parts.append(f"🎯 Mission: Sweep PDH ({pdh})")
            notes_parts.append("📝 Setelah sweep PDH, harga ikut struktur & trend")

        elif bias == "DOWN":
            if current_open < pivots["PP"]:
                notes_parts.append("⚠️ Open < Pivot → PP entry INVALID (sudah di bawah)")
                entry_levels.append(("R1 (Sell Zone)", pivots["R1"]))
                notes_parts.append("✅ R1 masih valid sebagai sell zone")
            else:
                entry_levels.append(("Pivot (Sell Zone)", pivots["PP"]))
                entry_levels.append(("R1 (Sell Zone)", pivots["R1"]))
                notes_parts.append("✅ PP dan R1 valid sebagai sell zone")

            notes_parts.append(f"🎯 Mission: Sweep PDL ({pdl})")
            notes_parts.append("📝 Setelah sweep PDL, harga ikut struktur & trend")

        else:  # NEUTRAL
            notes_parts.append("⚖️ Open = Previous Open → NEUTRAL, tidak ada bias")
            notes_parts.append("⏳ Tunggu konfirmasi arah selanjutnya")

        return entry_levels, "\n".join(notes_parts)

    def _get_invalidation(self, bias: str, pivots: dict, pdh: float, pdl: float) -> str:
        """Determine invalidation level."""
        if bias == "UP":
            return f"Below S2 ({pivots['S2']})"
        elif bias == "DOWN":
            return f"Above R2 ({pivots['R2']})"
        else:
            return "N/A (Neutral bias)"

    def _get_target(self, bias: str, pdh: float, pdl: float, pivots: dict) -> str:
        """Determine target based on bias."""
        if bias == "UP":
            return f"PDH: {pdh} → kemudian R1: {pivots['R1']}"
        elif bias == "DOWN":
            return f"PDL: {pdl} → kemudian S1: {pivots['S1']}"
        else:
            return "N/A"

    def format_signal(self, signal: QuantumSignal, pivots: dict) -> str:
        """Format the signal into a Telegram-ready message."""

        # Emoji based on bias
        if signal.bias == "UP":
            bias_emoji = "🟢🔼"
            direction = "BULLISH BIAS"
        elif signal.bias == "DOWN":
            bias_emoji = "🔴🔽"
            direction = "BEARISH BIAS"
        else:
            bias_emoji = "⚖️"
            direction = "NEUTRAL"

        # SMC quality indicator
        smc_badge = ""
        if signal.smc_analysis:
            score = signal.smc_analysis.confluence_score
            if score >= 70:
                smc_badge = " | 🔥 SMC: HIGH"
            elif score >= 50:
                smc_badge = " | ⚡ SMC: MED"
            elif score >= 30:
                smc_badge = " | ⚠️ SMC: LOW"
            else:
                smc_badge = " | ❌ SMC: SKIP"

        lines = [
            f"{bias_emoji} *QUANTUM SIGNAL — {signal.symbol}*{smc_badge}",
            f"━━━━━━━━━━━━━━━━━━━━━━━━━",
            f"",
            f"📐 *Bias:* `{direction}`",
        ]

        # SMC signal quality warning
        if signal.smc_filtered:
            lines.append(f"🚨 *SIGNAL FILTERED — Low SMC confluence*")
            lines.append(f"")

        lines.append(f"")
        lines.append(f"🎯 *Entry Levels:*")

        if signal.entry_levels:
            for name, price in signal.entry_levels:
                lines.append(f"  → {name}: `{price}`")
        else:
            lines.append("  → Tidak ada entry valid saat ini")

        lines.extend([
            f"",
            f"🛡️ *Invalidation:* `{signal.invalidation}`",
            f"🏁 *Target:* `{signal.target}`",
            f"",
            f"━━━━━━━━━━━━━━━━━━━━━━━━━",
            f"📊 *Pivot Levels:*",
            f"  R3: `{pivots['R3']}`",
            f"  R2: `{pivots['R2']}`",
            f"  R1: `{pivots['R1']}`",
            f"  PP: `{pivots['PP']}`",
            f"  S1: `{pivots['S1']}`",
            f"  S2: `{pivots['S2']}`",
            f"  S3: `{pivots['S3']}`",
        ])

        # SMC Details section
        if signal.smc_analysis:
            smc = signal.smc_analysis
            lines.extend([
                f"",
                f"━━━━━━━━━━━━━━━━━━━━━━━━━",
                f"🏦 *Smart Money Concepts:*",
                f"  📐 Structure: `{smc.market_structure.upper()}`",
                f"  📍 Zone: `{smc.zone.upper()}`",
                f"  🎯 Score: `{smc.confluence_score}/100`",
            ])
            if smc.nearest_ob:
                ob = smc.nearest_ob
                lines.append(f"  🧱 OB: `{ob.low:.5g} - {ob.high:.5g}`")
            if smc.nearest_fvg:
                fvg = smc.nearest_fvg
                lines.append(f"  📊 FVG: `{fvg.low:.5g} - {fvg.high:.5g}`")
            if smc.liquidity_swept:
                lines.append(f"  💧 Liquidity: `{smc.sweep_direction}` swept")

            # Recommendation
            rec = SMCEngine.get_signal_recommendation(smc.confluence_score)
            lines.append(f"  {rec}")

        lines.extend([
            f"",
            f"━━━━━━━━━━━━━━━━━━━━━━━━━",
            f"📝 *Notes:*",
            f"{signal.notes}",
            f"",
            f"⚠️ _Disclaimer: Bukan financial advice. DYOR!_",
        ])

        return "\n".join(lines)
